package com.swctools.common.enums;

public enum BundleKeys {
    SILENT_UPDATE("SILENT_UPDATE"),

    LAYOUT_TYPE("LAYOUT_TYPE"),
    LAYOUT_JSON_STRING("LAYOUT_JSON_STRING"),

    DIALOG_TITLE("DIALOG_TITLE"),
    DIALOG_MESSAGE("DIALOG_MESSAGE"),
    DIALOG_COMMAND("DIALOG_COMMAND"),
    DIALOG_VALUE("DIALOG_VALUE"),

    DIALOG_SPINNER_STRING_ARRAY("DIALOG_SPINNER_STRING_ARRAY"),

    PROGRESS_RUNNING("DIALOG_RUNNING"),
    PROGRESS_MESSAGE("PROGRESS_MESSAGE"),
    PROGRESS_INDETERMINATE("PROGRESS_INDETERMINATE"),
    FAB_STATE("FAB_STATE"),
    DOWNLOADING("DOWNLOADING"),
    PLAYER_ID("PLAYER_ID"),
    PLAYER_NAME("PLAYER_NAME"),
    PLAYER_FACTION("PLAYER_FACTION"),

    VISIT_RESPONSE("VISIT_RESPONSE"),
    LOGIN_RESPONSE("LOGIN_RESPONSE"),
    PLAYER_MODEL("PLAYER_MODEL"),
    BATTLE_LOG("BATTLE_LOG"),
    DEFENCE_NOTIFICATION_LOG("DEFENCE_NOTIFICATION_LOG"),
    GUILDPUBLIC("GUILDPUBLIC"),

    LAYOUT_FILTER_PLAYER("LAYOUT_FILTER_PLAYER"),
    LAYOUT_FILTER_FACTION("LAYOUT_FILTER_FACTION"),
    LAYOUT_FILTER_TYPE("LAYOUT_FILTER_TYPE"),
    LAYOUT_FILTER_TAG("LAYOUT_FILTER_TAG"),
    LAYOUT_FILTER_WILDCARD("LAYOUT_FILTER_WILDCARD"),
    LAYOUT_FILTER_FAV("LAYOUT_FILTER_FAV"),

    LAYOUT_SEARCHED("LAYOUT_SEARCHED"),
    LAYOUT_FILTERED("LAYOUT_FILTERED"),
    LAYOUT_SEARCHSTR("LAYOUT_SEARCHSTR"),
    LAYOUT_FOLDER_BREADCRUMB_ARRAY("LAYOUT_FOLDER_BREADCRUMB_ARRAY"),
    TMP_LAYOUT_FOLDER_BREADCRUMB_ARRAY("TMP_LAYOUT_FOLDER_BREADCRUMB_ARRAY"),


    LAYOUT_VERSION("LAYOUT_VERSION"),
    LAYOUT_VERSION_ID("LAYOUT_VERSION_ID"),
    LAYOUT_TAG("LAYOUT_TAG"),
    LAYOUT_ID("LAYOUT_ID"),
    LAYOUT_NAME("LAYOUT_NAME"),
    LAYOUT_IMAGE("LAYOUT_IMAGE"),
    LAYOUT_FAV("LAYOUT_FAV"),

    ROW_ID("ROW_ID"),
    ACTIVITY_MODE("ACTIVITY_MODE"),

    LAYOUT_FOLDER_ID("LAYOUT_FOLDER_ID"),
    PARENT_LAYOUT_FOLDER_ID("PARENT_LAYOUT_FOLDER_ID"),
    LAYOUT_FOLDER_TO_MOVE("LAYOUT_FOLDER_SELECTED"),
    LAYOUT_RECORD("LAYOUT_RECORD"),
    HIT_LIST_RESULT("HIT_LIST_RESULT"),
    HIT_LIST_GUILD("HIT_LIST_GUILD"),

    PROTECTED_UNTIL_STR("PROTECTED_UNTIL_STR"),
    PROTECTED_UNTIL_LNG("PROTECTED_UNTIL_LNG"),

    CREDIT_AMT_TXT("CREDIT_AMT_TXT"),
    ALLOY_AMT_TXT("ALLOY_AMT_TXT"),
    CONTRA_AMT_TXT("CONTRA_AMT_TXT"),

    CREDIT_CAP("CREDIT_CAP"),
    CREDIT_AMT("CREDIT_AMT"),
    ALLOY_CAP("ALLOY_CAP"),
    ALLOY_AMT("ALLOY_AMT"),
    CONTRA_CAP("CONTRA_CAP"),
    CONTRA_AMT("CONTRA_AMT"),

    DEKOARRAYLIST("DEKOARRAYLIST"),
    GUILDNAME("GUILDNAME"),
    SCIMAGEID("SCIMAGEID"),
    ARMOURYIMAGEID("ARMOURYIMAGEID"),
    SCTACTITEM("SCTACTITEM"),
    PLAYERTRAPS("PLAYERTRAPS"),
    ARMOURYTACTITEM("ARMOURYTACTITEM"),
    PLAYERTROOPS("PLAYERTROOPS"),
    PLAYERHEROES("PLAYERHEROES"),
    PLAYERAIR("PLAYERAIR"),
    PLAYERMEDALS("PLAYERMEDALS"),
    PLAYERBASESCORE("PLAYERBASESCORE"),
    PLAYERREPUTATION("PLAYERREPUTATION"),
    PLAYERCRYSTALS("PLAYERCRYSTALS"),
    ATTACKSWON("ATTACKSWON"),
    DEFENCESWON("ATTACKSWON"),

    DATA_TABLES_TO_UPDATE("DATA_TABLES_TO_UPDATE"),
    MANIFESTVERSION("MANIFESTVERSION"),
    MANIFESTURL("MANIFESTURL"),
    PATCHESFILE("PATCHESFILE"),
    WARPARTICIPANT("WARPARTICIPANT"),
    PREV_SCREEN("PREV_SCREEN"),
    GUILD_ID("GUILD_ID"),
    EQUIPMENT_IDS("EQUIPMENT_IDS"),
    RUNNABLE_PROGRESS_MESSAGE("RUNNABLE_PROGRESS_MESSAGE"),
    WAR_ID("WAR_ID")
    ;


    private final String bundleKey;

    BundleKeys(String bKey) {
        this.bundleKey = bKey;
    }

    public String toString() {
        return this.bundleKey;
    }
}
