package com.swctools.common.enums;

public enum ServerConstants {
    STATUS_CODE_NOT_MODIFIED(14),
    STATUS_CODE_BAD_INPUT(701),
    STATUS_AUTHENTICATION_FAILED(800),
    STATUS_AUTHORIZATION_FAILED(801),
    LOGIN_TIME_MISMATCH(917),
    STATUS_CODE_EXTERNAL_ACCOUNT_AUTH_FAILURE(1318),
    INACTIVE_PLAYER_IDENTITY(1900),
    DESYNC_BANNED(1999),
    STATUS_CODE_PVP_TARGET_IS_UNDER_PROTECTION(2100),
    STATUS_CODE_PVP_TARGET_IS_UNDER_ATTACK(2101),
    STATUS_CODE_PVP_TARGET_IS_ONLINE(2102),
    STATUS_CODE_PVP_TARGET_NOT_FOUND(2103),
    STATUS_CODE_PVP_TARGET_BANNED(2104),
    STATUS_CODE_PVP_TARGET_IS_INVALID(2105),
    STATUS_CODE_PVP_TARGET_PLANET_MISMATCH(2106),
    STATUS_CODE_PVP_TARGET_HAS_RELOCATED(2107),
    REPLAY_DATA_NOT_FOUND(2110),
    STATUS_CODE_ALREADY_REGISTERED(2200),
    STATUS_CODE_PERMANENTLY_LINKED(2201),
    STATUS_CODE_GUILD_MIN(2300),
    STATUS_CODE_ALREADY_IN_A_GUILD(2300),
    STATUS_CODE_GUILD_NAME_TAKEN(2301),
    STATUS_CODE_GUILD_IS_FULL(2302),
    STATUS_CODE_GUILD_NOT_OPEN_ENROLLMENT(2303),
    STATUS_CODE_GUILD_SCORE_REQ_NOT_MET(2304),
    STATUS_CODE_GUILD_WRONG_FACTION(2305),
    STATUS_CODE_NOT_IN_GUILD(2306),
    STATUS_CODE_NOT_ENOUGH_GUILD_RANK(2309),
    STATUS_CODE_NOT_IN_SAME_GUILD(2315),
    STATUS_CODE_CANNOT_DEDUCT_NEGATIVE_AMOUNT(2316),
    STATUS_CODE_CAN_ONLY_DONATE_TROOPS(2318),
    STATUS_CODE_NOT_ENOUGH_GUILD_TROOP_CAPACITY(2319),
    STATUS_CODE_TOO_SOON_TO_REQUEST_TROOPS_AGAIN(2320),
    STATUS_CODE_PLAYER_IS_IN_SQUAD_WAR(2321),
    STATUS_CODE_GUILD_MAX(2322),
    STATUS_CODE_GUILD_WAR_BASE_ALREADY_OWNED(2402),
    STATUS_CODE_GUILD_WAR_BASE_UNDER_ATTACK(2403),
    STATUS_CODE_GUILD_WAR_PARTICIPANT_IN_ATTACK(2404),
    STATUS_CODE_GUILD_WAR_NOT_ENOUGH_TURNS(2406),
    STATUS_CODE_GUILD_WAR_NOT_ENOUGH_VICTORY_POINTS(2407),
    STATUS_CODE_GUILD_WAR_WRONG_PHASE(2409),
    STATUS_CODE_GUILD_WAR_CANNOT_CLAIM_EXPIRED_REWARD(2413),
    STATUS_CODE_GUILD_WAR_EXPIRED(2414),
    STATUS_CODE_GUILD_WAR_PLAYER_UNDER_ATTACK(2418),
    STATUS_CODE_GUILD_WAR_BUFF_BASE_OWNER_CHANGE(2421),
    STATUS_CODE_CANNOT_UNLOCK_ALREADY_AVAILABLE_PERK(2502),
    STATUS_CODE_CANNOT_UPGRADE_PERK_NONSEQUENTIALLY(2504),
    DEACTIVATE_EQUIPMENT_FAILED(2604),
    RECEIPT_STATUS_COMPLETE(0),
    RECEIPT_STATUS_INITIATED(6300),
    AGREE_TO_ZYNGA_TERMS(2001),
    //discovered - may be inaccurate
//	ZERO(0),
    SUCCESS(5001),
    UNKNOWN_AUTHENTICATION_PROBLEM(802),
    /// Timestamp specified is too small
    COMMAND_TIMESTAMP_ERROR(909),
    /// Timestamp specified is too big
    COMMAND_TIMESTAMP_ERROR2(911),
    BUILDING_DOESNT_EXIST(1008),
    BUILDING_OVERLAP_WITH_ANOTHER(1010),
    BUILDING_OUT_OF_MAP(1011),
    APP_BLEW_UP(-1),

    ///OTHER STUFF
    JUNK_ON_PVP_BASE_CLEAR_BEFORE_TRYING_AGAIN(2420);

    private int serverConst;

    ServerConstants(int code) {
        this.serverConst = code;
    }

    public int toInt() {
        return serverConst;

    }
}
